# Generated by Django 3.2.4 on 2021-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
